"""user tokens added to users model

Revision ID: 43227c8b7918
Revises: 5aa73e161797
Create Date: 2019-12-28 01:49:50.053908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43227c8b7918'
down_revision = '5aa73e161797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('api_token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_api_token'), 'user', ['api_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_token'), table_name='user')
    op.drop_column('user', 'api_token_expiration')
    op.drop_column('user', 'api_token')
    # ### end Alembic commands ###
